In [ ]:
# import numpy as np
import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt
import os
from collections import Counter

In [71]:
df = pd.read_csv('data.csv')
df.head(100)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
0,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015
1,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015
2,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015
3,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015
4,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,tt3203606,1.316239,15000000,8235661,Trumbo,Bryan Cranston|Diane Lane|Helen Mirren|Elle Fa...,Jay Roach,Are you now or have you ever been...,The career of screenwriter Dalton Trumbo is ha...,124,Drama,Groundswell Productions|Inimitable Pictures|Sh...,10/27/2015,273,7.2,2015
96,tt1741273,1.315266,19500000,32189727,Secret in Their Eyes,Chiwetel Ejiofor|Nicole Kidman|Julia Roberts|D...,Billy Ray,Don't look back,"A tight-knit team of FBI investigators, along ...",111,Crime|Drama|Mystery,Ingenious Media|Gran Via Productions|IM Global...,10/14/2015,202,6.2,2015
97,tt2279373,1.291013,74000000,311594032,The SpongeBob Movie: Sponge Out of Water,Tom Kenny|Bill Fagerbakke|Rodger Bumpass|Clanc...,Paul Tibbitt,He's leaving his world behind.,Burger Beard is a pirate who is in search of t...,93,Family|Animation,Paramount Pictures|Nickelodeon Movies|Nickelod...,2/5/2015,533,5.7,2015
98,tt3369806,1.278928,20000000,43967255,Max,Thomas Haden Church|Josh Wiggins|Lauren Graham...,Boaz Yakin,Best Friend. Hero. Marine.,A dog that helped soldiers in Afghanistan retu...,111,Adventure|Drama|Family,Sunswept Entertainment|Warner Bros.|Metro-Gold...,6/26/2015,214,7.0,2015
99,tt2515034,1.225325,40000000,10664749,The Gunman,Sean Penn|Jasmine Trinca|Javier Bardem|Ray Win...,Pierre Morel,Armed With the Truth.,Eight years after fleeing the Congo following ...,115,Action|Drama|Crime,StudioCanal|Silver Pictures|TF1 Films Producti...,2/16/2015,283,5.6,2015

In [ ]:
# У какого фильма из списка самый большой бюджет?


df[df.budget == df.budget.max()]
# ответ The Warrior's Way

In [ ]:
# Какой из фильмов самый длительный (в минутах)?

df[df.runtime == df.runtime.max()]
# ответ Gods and Generals

In [ ]:
# Какой из фильмов самый короткий (в минутах)?

df[df.runtime == df.runtime.min()]
# ответ Winnie the Pooh

In [ ]:
# Какое число ближе к средней длительности фильма в датасете?

df.runtime.mean()
# ответ 110

In [ ]:
# Какое число ближе к медианной длительности фильма в датасете?

df.runtime.median()
# ответ 106

In [77]:
# Какой самый прибыльный фильм?
#  Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма.

df['profit'] = df.revenue - df.budget # в DF добавляем колонку с расчитанным доходом/расходом. Для дальнейшего использования
df[df.profit == df.profit.max()]

# ответ Avatar

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,profit
239,tt0499549,9.432768,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,8458,7.1,2009,2544505847

In [ ]:
# Какой фильм самый убыточный?

df[df.profit == df.profit.min()]
# ответ The Warrior's Way

In [ ]:
# У скольких фильмов из датасета объем сборов оказался выше бюджета?

df[df.profit > 0].original_title.count() #считаем количество фильмов с доходом больше 0

# ответ 1478

In [ ]:
# Какой фильм оказался самым кассовым в 2008 году?

reven = df[df.release_year == 2008].revenue.max() # определяем размер максимальной кассы фильмов из 2008
df[df.revenue == reven] # извлекаем данные по условию

# ответ The Dark Knight

In [ ]:
# Самый убыточный фильм за период с 2012 по 2014 гг. (включительно)?

df[df.profit == (df.query('2012 <= release_year <= 2014').profit.min())] # сортируем по году и максимальному убытку
# ответ The Lone Ranger

In [ ]:
# Какого жанра фильмов больше всего?
import collections

genres = df.genres.str.split('|')

genre = Counter()

for gen in genres:
    genre += Counter(gen)
genre.most_common()
# ответ ('Drama', 782)

In [ ]:
# Какого жанра среди прибыльных фильмов больше всего?

profit_movies = df[df.profit > 0]
profit_movies
genres = profit_movies.genres.str.split('|')
genre = Counter()

for gen in genres:
    genre += Counter(gen)
genre.most_common()
# ответ ('Drama', 560)

In [ ]:
# Кто из режиссеров снял больше всего фильмов?
df['director'].value_counts()
# ответ Steven Soderbergh  13

In [ ]:
# Кто из режиссеров снял больше всего прибыльных фильмов?
profit_movies = df[df.profit > 0]
profit_movies
profit_movies.director.value_counts()
# ответ Ridley Scott 12

In [123]:
# Кто из режиссеров принес больше всего прибыли?
df1 = pd.pivot_table(df, values = 'profit', 
                     index = 'director', 
                     aggfunc = sum).sort_values('profit', ascending = False).head(1)
df1.index
# ответ Peter Jackson	5202593685

Index(['Peter Jackson'], dtype='object', name='director')

In [ ]:
# Какой актер принес больше всего прибыли?
df_cast = pd.DataFrame(df.cast.str.split('|').tolist()).stack().reset_index()
df_cast.columns = ['row_index','row2','cast']
df_cast['profit_cast'] = df_cast.row_index.apply(lambda x : df.iloc[x]['profit'])
table = pd.pivot_table(df_cast, values = 'profit_cast', index = 'cast', aggfunc = sum).sort_values('profit_cast', ascending = False)
table

# ответ Emma Watson

In [ ]:
#  Какой актер принес меньше всего прибыли в 2012 году?